### ISSUE TITLE
Incorrect number of vulnerabilities sent

### ISSUE THREAD

**Issue by thenaturalist** [kunalnagarco/action-cve#137]
Hi there, 
for a vanilla config of the action posting to slack, the action correctly sends the alert. 

However, it's an incorrect (as in, too low) number. 

It's noteworthy that

a) the number sent is matching with relatively younger issues. 
b) much older issues are missing and changing `count` has no effect on number reported. 

Is there a hardcoded lookback window in the action?

**Comment by kunalnagar** [comment]
@thenaturalist - for Slack, there's a [max count of 30 vulns](https://github.com/kunalnagarco/action-cve/blob/main/src/destinations/slack.ts#L18) that are sent. This is because [Slack truncates messages after 40,000 characters](https://api.slack.com/methods/chat.postMessage#truncating).

So, even though you may have more than 30 vulns in your repo, only 30 will be included in the message. However, the action does include a [blurb about this as a warning](https://github.com/kunalnagarco/action-cve/blob/main/src/destinations/slack.ts#L56-L58).

Hope this helps!
