### ISSUE TITLE
400 Request Error

### ISSUE THREAD

**Issue by m-standfuss** [kunalnagarco/action-cve#74]
When running this to publish to a slack webhook it throws a 400 error. 

```Error: Error: An HTTP protocol error occurred: statusCode = 400```

Here is my action yaml, commented out the schedule for an on push while I was troubleshooting the issue. 

```name: 'Check for Vulnerabilities'

#on:
#  schedule:
#    - cron: '* * * * *' # every 6 hours

on: push

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: kunalnagarco/action-cve@v1.6.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_DEVOPS }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          count: 100

**Comment by m-standfuss** [comment]
Also confirmed that its not an issue with the secrets as I hardcoded the values into the direct yml and same result

**Comment by varunranipeta** [comment]
Im having the same issue and I have a very similar YAML

**Comment by kunalnagar** [comment]
@m-standfuss @varunranipeta could you post a sample Slack Webhook URL that y'all are using? Please be sure to redact any info as necessary, thanks!

**Comment by kunalnagar** [comment]
@m-standfuss 

> Error: Error: An HTTP protocol error occurred: statusCode = 400

Is this the only information that Slack provides? 400 is generally considered a Bad Request which might indicate a malformed Slack Webhook URL? 🤷 

Here's the logic for checking the format of the Slack Webhook URL if you want to double-check

https://github.com/kunalnagarco/action-cve/blob/b942a084862380686a6392fe41e5bc992d76d10b/src/destinations/slack.ts#L52-L57

**Comment by S1rRV** [comment]
@m-standfuss I have debugged the issue. It is the length of the message. Slack does not allow a message that is larger than 40,000 characters and will throw a 400 error. Reduce the count to 10-50 (based on how many alerts you have) 

cc: @kunalnagar you may want to add this to the wiki

**Comment by kunalnagar** [comment]
@S1rRV - thanks for debugging this! 🎉  

i see a few possible next actions here:

- since this limitation only applies to Slack (or maybe even Teams 🤷), we can enforce a max count limit and surface that error when those options are chosen
- we can apply a global rule to the max count - imo, that doesn't make a lot of sense for users who choose other options 🤔 
- we keep the same model, and i just update the wiki and add some comments in the action docs

which path do you think would offer the best UX?

**Comment by alexandru-mohora-rm** [comment]
I consider the best approach to be option 1, however maybe a workaround would be to be able to filter by severity (and you might never hit the error).

**Comment by kunalnagar** [comment]
@alexandru-mohora-rm - great suggestion for a new feature as the filtering could apply to all destinations! 👍 

To solve this particular issue, I am leaning towards option 1 as it only impacts Slack.

**Comment by S1rRV** [comment]
@kunalnagar I agree with @alexandru-mohora-rm 

The best approach is Option 1 but we may be able to make the whole action much better with filters like Severity, Manifest file (packlock.json or gemfile etc), ecosystem (ruby/npm/maven etc)

**Comment by kunalnagar** [comment]
@S1rRV @alexandru-mohora-rm - This is how I'm thinking of implementing this "max count" limit i.e. a note in the actual message sent to Slack informing the user that there were `x` alerts but we sent `max count` alerts because of message length restrictions. 

![image](https://user-images.githubusercontent.com/2741371/177922611-0b87ace4-3be2-4f71-bf47-9e1874a4dd3b.png)

I think the primary benefit of this approach is that **it does not fail the action** since this is a Slack limitation. If the user has other destinations, and we fail the action run just for Slack, all of them will fail.

I did some testing with varying message lengths and found that a max count of `40` alerts works really well.
